name: Hello World Action

# Triggers the workflow on push to the 'main' branch
on:
  push:
    branches:
    - main

jobs:
  say-hello:
    runs-on: self-hosted
    container:
      image: alpine:3.18.3
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: multiple
      run: |
        pwd &&
        echo "---" &&
        ls -la &&
        echo "---" &&
        env &&
        echo "---" &&
        cat /etc/os-release &&
        true
